# Numpy

![Scalar Vector Matrix Tensor](https://res.cloudinary.com/practicaldev/image/fetch/s--oTgfo1EL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://raw.githubusercontent.com/adhiraiyan/DeepLearningWithTF2.0/master/notebooks/figures/fig0201a.png)

In [ ]:
import numpy as np

In [ ]:
a = np.array([10, 20, 30, 40, 50, 60])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [ ]:
type(a[3])

numpy.int32

In [ ]:
a[2] *= 2
print(a[2])

60


In [ ]:
a

array([10, 20, 60, 40, 50, 60])

In [ ]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(b)
print(b.shape)
print(b.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
int32


In [ ]:
a = np.array([10, 20, 30, 40, 50, 60])
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [ ]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [ ]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [ ]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26])

In [ ]:
np.max(a)

60

In [ ]:
np.min(a)

10

In [ ]:
np.argmax(a) #maximum değerin indexini verir

5

In [ ]:
np.mean(a)

35.0

In [ ]:
np.median(a)

35.0

In [ ]:
np.std(a)

17.07825127659933

In [ ]:
b

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
# axis=1 => Row
# axis=0 => Column
np.sum(b, axis=0)

array([50, 70, 90])

In [ ]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
full = np.full((3, 3), 8)
print(full)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [ ]:
eye = np.eye(9)
print(eye)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
arange = np.arange(7)
print(arange)

arange = np.arange(0, 10, 2)
print(arange)

[0 1 2 3 4 5 6]
[0 2 4 6 8]


In [ ]:
# Create randint
random = np.random.random((3, 3))
print(random)

[[0.96472088 0.97336887 0.25534287]
 [0.26403895 0.36357651 0.86289624]
 [0.0803913  0.76478255 0.6622259 ]]


In [ ]:
arr = np.random.randint(20, size=(5, 5))
print(arr)

[[ 5 10  8 19 14]
 [ 1 14 11  9 11]
 [17  8  1 18  2]
 [ 9 17 14  2  0]
 [19  0 18  2  7]]


In [ ]:
zeros*6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr

array([[ 5, 10,  8, 19, 14],
       [ 1, 14, 11,  9, 11],
       [17,  8,  1, 18,  2],
       [ 9, 17, 14,  2,  0],
       [19,  0, 18,  2,  7]])

In [ ]:
arr[0:3, 0:4]
#arr[satır, sütun]

array([[ 5, 10,  8, 19],
       [ 1, 14, 11,  9],
       [17,  8,  1, 18]])

In [ ]:
arr[arr > 10]

array([19, 14, 14, 11, 11, 17, 18, 17, 14, 19, 18])

In [ ]:
np.where(arr > 10)

(array([0, 0, 1, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([3, 4, 1, 2, 4, 0, 3, 1, 2, 0, 2], dtype=int64))

In [ ]:
np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]).reshape(3, -1).shape

(3, 4)

In [ ]:
c = np.random.randint(10, size=(3, 3))
print(c)
c_inv = np.linalg.inv(c)
print(c_inv)
#matrisin tersini verir


[[5 8 5]
 [6 9 4]
 [2 9 6]]
[[ 0.39130435 -0.06521739 -0.2826087 ]
 [-0.60869565  0.43478261  0.2173913 ]
 [ 0.7826087  -0.63043478 -0.06521739]]


## Dot product
![Dot product](https://algebra1course.files.wordpress.com/2013/02/slide10.jpg)

credit: https://algebra1course.files.wordpress.com/

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(a.shape)

(2, 3)


In [ ]:
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])
b = b.reshape(3,2)
print(b.shape)

(3, 2)


In [ ]:
axb = np.dot(a, b)
axb

array([[ 58,  64],
       [139, 154]])

In [ ]:
# Transpose
(b.T).shape

(2, 3)